### ISSUE TITLE
Module not Found

### ISSUE THREAD

**Issue by jkaliski** [Galaco/react-mailerlite-form#3]
Adding dependency via npm i @galaco/... and importing it into a .js file via import MailerLite from "@galaco/..." results in an error: 

Could not resolve MailerLite 

Module not found

Env:
React / Next (up to date)
Node 14

**Comment by Galaco** [comment]
Hi! Thank you for bringing this to my attention!

To be totally honest, I unfortunately have no time to support this module. I suggest either forking it and publishing your own, or taking the source and building your own component; given the simplicity of the provided component this would likely be easier and fast than waiting on me to do anything. I'll be marking this repo as archived.

Sorry it's not more favorable news 🙇
